[Database]
DB_ENGINE = 'sqlite3'
DB_PATH = "./database.db"
# DB_PATH = "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"

[Application]
PORT = 8080

[FileStorage]
SYSTEM_PATH = './tmp/storage'